name: Generate Visualization

on:
  workflow_dispatch: # execute manually
  schedule: # execute every 2 days
    - cron: "0 0 */2 * *"
  push: {branches: ["master", "main"]}

jobs:
  # summary-cards:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Summary Cards
  #       uses: vn7n24fzkq/github-profile-summary-cards@release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         USERNAME: ${{ github.repository_owner }}

#  snake-animation:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Generate Snake Animation
#        uses: Platane/snk@master
#        id: snake-gif
#        with:
#          github_user_name: rliuup
#          svg_out_path: dist/github-contribution-grid-snake.svg

#      - name: Publish Snake Animation SVG
#        uses: crazy-max/ghaction-github-pages@v2.1.3
#        with:
#          target_branch: output
#          build_dir: dist
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  metrics-achievements:
    runs-on: ubuntu-latest
    steps:
      - name: Achievements metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.README_ACCESS_TOKEN }}
          output_action: gist
          committer_gist: 4299c22ef019b0ee1c1495b6840eed47
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut  # Hide octonaut achievement
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params

  metrics-github:
    runs-on: ubuntu-latest
    steps:
      - name: Github metrics
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.README_ACCESS_TOKEN }}
          output_action: gist
          committer_gist: 4299c22ef019b0ee1c1495b6840eed47

  metrics-github-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.README_ACCESS_TOKEN }}
          output_action: gist
          committer_gist: 4299c22ef019b0ee1c1495b6840eed47
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year


  metrics-github-language:
    runs-on: ubuntu-latest
    steps:
      - name: Languages activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.language.svg
          token: ${{ secrets.README_ACCESS_TOKEN }}
          output_action: gist
          committer_gist: 4299c22ef019b0ee1c1495b6840eed47
          base: ""
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
